# Generated by Django 3.2.16 on 2022-12-02 17:10

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221130_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[recipes.validators.validate_color], verbose_name='Цвет в HEX'),
        ),
    ]
