# Generated by Django 3.2.16 on 2022-12-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221221_2300'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_favorite_model',
        ),
    ]
